### ISSUE TITLE
Add blocks placed counter to FastBuilder

### ISSUE THREAD

**Issue by TehTreeman** [McPlayHDnet/McPlayHD.net#10]
We already discussed that i believe,

**Comment by McPlayHD** [comment]
One way to solve this would be to put the IP "McPlayHD.net" in the Title of the Scoreboard instead of "FastBuilder" (because everyone knows that it's FastBuilder)
Like that we could create new space for more important information like the number of blocks placed.

**Comment by TehTreeman** [comment]
Yes that's a good idea
