### ISSUE TITLE
Bug with stats hologram in MS

### ISSUE THREAD

**Issue by obvTiger** [McPlayHDnet/McPlayHD.net#149]
The hologram in MS shows if nicked the stats of the nick, not the player that is playing.

![grafik](https://user-images.githubusercontent.com/83970850/154664845-a6f1d8d1-e367-4bb5-a6f3-81c4d80a1d41.png)

**Comment by McPlayHD** [comment]
intended... What good would a nick be if everyone sees that you are actually the one playing?
