### ISSUE TITLE
Add Toggle for Friends being able to see Nicknames

### ISSUE THREAD

**Issue by Worldbuilder777** [McPlayHDnet/McPlayHD.net#15]
At the moment, there is apparently an issue with people snitching on others in their friend list regarding their true identity behind a nickname, so a toggle would be nice that makes it possible to choose if you want to let your friends see your real name in a game.

**Comment by McPlayHD** [comment]
I'm moving this suggestion into the list provided in https://github.com/McPlayHDnet/McPlayHD.net/issues/105.
It will most likely also be implemented as a global setting and not as player-specific setting so you can only choose to let all friends either see your real name or none at all.
