### ISSUE TITLE
Minesweeper Pressure Plate Bug

### ISSUE THREAD

**Issue by Worldbuilder777** [McPlayHDnet/McPlayHD.net#164]
Walking on a pressure plate with the 'Spectate' item in hand soft locks you in the game as the pressure plate seems to trigger the Spectate menu repeatedly.

**Comment by Worldbuilder777** [comment]
This works with Stone, Heavy and Light Pressure Plates. (Tested on the maps Erebor and Courtyard)

**Comment by McPlayHD** [comment]
Fixed. Thanks for the report.
