### ISSUE TITLE
Display premium expiration 

### ISSUE THREAD

**Issue by TrooperCH** [McPlayHDnet/McPlayHD.net#19]
Add line on lobby scoreboard that shows when your rank expires

**Comment by McPlayHD** [comment]
in theory, this should work on the next BungeeCord restart tomorrow at 07:00

**Comment by McPlayHD** [comment]
Is implemented and seems to be working. it only updates every 2 seconds tho, so the last hour they will see a bit a weird countdown that updates every two seconds but I don't want to update every second as for now.
