### ISSUE TITLE
Fix Sam Message

### ISSUE THREAD

**Issue by maksch2** [McPlayHDnet/McPlayHD.net#20]
make ", to get to" also in yellow. 

![image](https://user-images.githubusercontent.com/69405201/92154216-bc629780-ee25-11ea-9348-991fcda4cf09.png)

**Comment by McPlayHD** [comment]
probably we won't change that because it's the same structure in German and therefore most likely intended to look like that.
![image](https://user-images.githubusercontent.com/7106489/92405153-4fa51100-f135-11ea-84f3-2bc91938045a.png)

**Comment by maksch2** [comment]
oh ok sorry my bad then
