### ISSUE TITLE
/ignore bug

### ISSUE THREAD

**Issue by Censhal** [McPlayHDnet/McPlayHD.net#21]
Whenever I /ignore someone, they relog and the ignore wears off. zJet also had this problem on his stream.

**Comment by maksch2** [comment]
I tried it with a vip and didnt had the problem

**Comment by McPlayHD** [comment]
I need exact "how to reproduce" instructions or I can't resolve this issue

**Comment by Censhal** [comment]
So during zJet's stream, he did /ignore calebed for an hour. Calebed then relogged and was able to /msg zJet again.

**Comment by McPlayHD** [comment]
That's because `/msg` is not ignored by `/ignore`!
**Only** messages written in public chat will be ignored. To ignore `/msg` he could simply do `/friend remove Calebed`
