### ISSUE TITLE
FastBuilder: Add possibility to let parties play next to each other

### ISSUE THREAD

**Issue by TrooperCH** [McPlayHDnet/McPlayHD.net#24]
Add the possibility to let friends/party play on the islands next to each other.

Possibilities
-Island selector: Open a HUD that shows all islands and lets you swap to unused islands
-Algorithm: Set up an algorithm that puts parties next to each other (if possible)
-Lazy ass variation: Let parties fill in from the right instead of the left

**Comment by McPlayHD** [comment]
It's now possible to switch the arena but @McPlayHDnet/admins or @McPlayHDnet/mods someone should probably write a #news for that. Whoever does it can close this issue I guess except @TrooperCH thinks it should be done more with an algorithm so that party are next to each other automatically.

**Comment by Worldbuilder777** [comment]
You can now play next to your friends by jumping towards their island a bunch of times and landing on a free one next to them.
