### ISSUE TITLE
BW Glitch || Spawn Trapping (big glitch) - Maw

### ISSUE THREAD

**Issue by MawHealth** [McPlayHDnet/McPlayHD.net#28]
this can ruin someones gameplay
luckily i gave him those tp to island things to get him out
https://youtu.be/ueyGi8lygy8

**Comment by McPlayHD** [comment]
I guess people should spawn in the cobwebs and not up in the ceiling right?

**Comment by McPlayHD** [comment]
or does it also have something to do with the map? Like is there a room in there where you can't get in or out?

**Comment by Worldbuilder777** [comment]
Yes, there was a hollow space above the bed room, this bug already occurred a few months ago, but I thought, i had it fixed. If someone can confirm it is now in fact fixed, which it should be, we can close this issue.

**Comment by Worldbuilder777** [comment]
It is indeed fixed, I checked it.
