### ISSUE TITLE
Lobby Glitch || Cosmetic Glitch *lobby* - Maw

### ISSUE THREAD

**Issue by MawHealth** [McPlayHDnet/McPlayHD.net#29]
theres a secret little area down at quake, its no longer accessible due to the snow there
https://youtu.be/l3GCOYEMgKo

**Comment by McPlayHD** [comment]
What exactly do you mean? How is it a glitch with Cosmetics? Please specify.

**Comment by Worldbuilder777** [comment]
Yes, there is a room down there, however, it is not a glitch.

**Comment by McPlayHD** [comment]
If it is not a glitch... Why does @MawHealth then even know it's there? And why is he saying that the snow blocks the way?

**Comment by MawHealth** [comment]
its a glitch that you can no longer get down there,

**Comment by MawHealth** [comment]
you used to be able to mine block by block to get in there its no longer possible due to the snow blocking the way

**Comment by Worldbuilder777** [comment]
It wasn't intended for players to go down there in the first place, and I don't see accidentally removing an unintended feature as a "glitch". Is the anymore questions, or can I close this issue?

**Comment by MawHealth** [comment]
na, all doine thanks

**Comment by Worldbuilder777** [comment]
Okay, thank you for your participation :)
