### ISSUE TITLE
Beds spawn in BedWars even for teams who don't exist

### ISSUE THREAD

**Issue by Worldbuilder777** [McPlayHDnet/McPlayHD.net#30]
Players can currently join BedWars 8x1 Games in a party of two Players and Farm Bed Destroys

**Comment by McPlayHD** [comment]
Is this in the new or the old BedWars?

**Comment by McPlayHD** [comment]
I looked into the source code of BedWars and I found a piece of code which removes all the beds of teams that are empty.
This means, if @IDragonRiderI did implement this correctly, it should already work and therefore this issue is invalid.
