### ISSUE TITLE
FastBuilder - Infinite

### ISSUE THREAD

**Issue by SaiyanSteev** [McPlayHDnet/McPlayHD.net#34]
In Infinite mode (ik it’s in beta) If u jump off in the correct place you will be stuck falling in a loop.

I’ll upload a video of it on my yt and link here when done.

**Comment by McPlayHD** [comment]
Any updates on the video link?

**Comment by stupxd** [comment]
On some spots if you just **walk off** you'll get teleported on the island, but if you **jump off** you'll get stuck.
But there's a side where u can get stuck both by jumping and walking off.


https://user-images.githubusercontent.com/83234016/116115422-0ead3d00-a6c3-11eb-8d3e-94a3b1123653.mp4

**Comment by McPlayHD** [comment]
Fixed after next FastBuilder server restarts (latest in 24h)
