### ISSUE TITLE
./nick glitch no blocks (Fast builder)

### ISSUE THREAD

**Issue by MawHealth** [McPlayHDnet/McPlayHD.net#35]
if you nick while having noteblocks, you receive nothing in your inventory as your nicked man, its nothing major but its there o;

**Comment by MawHealth** [comment]
even if you jump off, you got nothing

**Comment by McPlayHD** [comment]
I found the error and was able to fix it. It actually was a bug not related to FastBuilder but to the Languages system... It's just such a special case when having selected a NoteBlock that it actually caused to crash the method and leaving you with an empty inventory.
Fixed after next FastBuilder restarts (latest in 24h)
