### ISSUE TITLE
infinity ender dragon eggs in the Lobby

### ISSUE THREAD

**Issue by OwOreo** [McPlayHDnet/McPlayHD.net#38]
In the lobby under Slender is a room. There we can find some E-Dragon eggs if u right-click them u spawn a new egg and the egg u right click respawns because of the map.
Clip: https://medal.tv/clips/49505003/d13376fnpbGV

**Comment by MawHealth** [comment]
this is intentional. you can summon the dragon if you spam this for around 2 hours

**Comment by OwOreo** [comment]
alr ty :)
