### ISSUE TITLE
Doublejump not getting reset when you land on fence

### ISSUE THREAD

**Issue by stupxd** [McPlayHDnet/McPlayHD.net#39]
https://user-images.githubusercontent.com/83234016/116111454-55009d00-a6bf-11eb-9941-2c5c2baa805b.mp4

So if you use doublejump on fence/land on it, it wont reset.

**Comment by McPlayHD** [comment]
Fixed in https://github.com/McPlayHDnet/LobbySystem/commit/cae691a2f964f4b55ff4c8ad2e0354e9b695facd
