### ISSUE TITLE
Colliding with Ender Dragon hitbox causing kick to limbus

### ISSUE THREAD

**Issue by stupxd** [McPlayHDnet/McPlayHD.net#41]
This happens like in ~70% of cases when dragon rushes on you. I think it could be fly checks that causing this.

https://user-images.githubusercontent.com/83234016/116524365-f82ffd00-a8df-11eb-9d3a-b383c8317a10.mp4

**Comment by stupxd** [comment]
Better clip I think.

https://user-images.githubusercontent.com/83234016/116525152-e733bb80-a8e0-11eb-825c-b990040dc09f.mp4

**Comment by stupxd** [comment]
Also dragon can punch armorstands, well in the end they come back but it looks pretty weird xd


https://user-images.githubusercontent.com/83234016/116526041-d6377a00-a8e1-11eb-9811-efa2933ddeba.mp4

**Comment by McPlayHD** [comment]
I honestly don't think we will fix that because it's just a lobby secret that hardly anyone knows about. I will most certainly always have more important things to fix than this.

**Comment by McPlayHD** [comment]
I changed a lot of things about the dragon special and there aren't so many packets sent to the player anymore (no longer change of biome to nether). So this might be fixed now. If not please reopen or create a new issue.
