### ISSUE TITLE
Using /nick while having no personal best in FastBuilder causes the nick to have an impossible PB

### ISSUE THREAD

**Issue by MudkiipMC** [McPlayHDnet/McPlayHD.net#43]
If a user who has no personal best in FastBuilder does /nick, the nickname will have an impossible pb, such as 2.249.

**Comment by McPlayHD** [comment]
Probably fixed in https://github.com/McPlayHDnet/FastBuilder/commit/9fc43e1f94be04c0def78f8661ddaae5f3da626b
Reopen this issue if still not fixed after 24 hours when all FB servers restarted.
