### ISSUE TITLE
Jukebox blocks bugged while using the /nick feature

### ISSUE THREAD

**Issue by MudkiipMC** [McPlayHDnet/McPlayHD.net#44]
While nicked, if you try to use any of the Jukebox blocks, you are unable to select them. However, all other premium blocks work. If Jukebox blocks are selected before using /nick, the player’s inventory will be empty. 
[jukebox bug video](https://youtu.be/9z23fCW-syI)

**Comment by McPlayHD** [comment]
Already mentioned in McPlayHDnet/McPlayHD.net/issues/35 and fixed a few minutes ago.
