### ISSUE TITLE
Bug in bedwars das man spectator sehen kann

### ISSUE THREAD

**Issue by obvTiger** [McPlayHDnet/McPlayHD.net#48]
Bug in bedwars das man spectator sehen kann und evtl., wenn sich spectator in den weg stellen kann man nicht mehr bridgen oder schlagen oder einfach mit Sachen interagtieren

Cutfehler bei 6 Sekunden sorry

Reproduzeieren: 
1. /me benutzen
2. leaven
3. warten bis wiederverbindung
4. nun kann man spectator sehen
https://user-images.githubusercontent.com/83970850/120063240-7eb63680-c066-11eb-880d-a91275195b0a.mp4

ich weiss nicht aber vielleicht hat es einen Zusammenhang mit der Party in der wir waren

**Comment by McPlayHD** [comment]
@obvTiger could you try to reproduce this issue now after my patch?

**Comment by obvTiger** [comment]
ok i will try

**Comment by obvTiger** [comment]
looks like its fixed
:D

**Comment by McPlayHD** [comment]
Ah perfect. Thx.
