### ISSUE TITLE
Bug in /votestart command

### ISSUE THREAD

**Issue by obvTiger** [McPlayHDnet/McPlayHD.net#49]
whem someone votestarts the message in German the last line is

werden, vote ebenfalls mit /votestart f den Rundenstart

i think the "f" should be a "für"

![grafik](https://user-images.githubusercontent.com/83970850/120371021-8e0edb80-c315-11eb-88a6-33bb2951a2c0.png)

**Comment by FabianSchaerer** [comment]
Fixed on next restart.

**Comment by Worldbuilder777** [comment]
Fixed on next restart.
