### ISSUE TITLE
CR lag / sudden TPS drop

### ISSUE THREAD

**Issue by stupxd** [McPlayHDnet/McPlayHD.net#52]
https://user-images.githubusercontent.com/83234016/121373465-c3d04780-c947-11eb-8929-1983e809e1fa.mp4

https://user-images.githubusercontent.com/83234016/121373470-c5017480-c947-11eb-909b-914070aadbd5.mp4

https://user-images.githubusercontent.com/83234016/121373475-c59a0b00-c947-11eb-8476-87e9b38b1b49.mp4

**Comment by stupxd** [comment]
Another couple of games with insane lag spikes. Its not my connection as you can see - everyone lags pretty badly.

https://user-images.githubusercontent.com/83234016/121379310-920daf80-c94c-11eb-8d92-746a8b64a9f4.mp4

https://user-images.githubusercontent.com/83234016/121379401-a8b40680-c94c-11eb-9e03-dea6bfe3f122.mp4


https://user-images.githubusercontent.com/83234016/121379522-c71a0200-c94c-11eb-964b-09678b8c76df.mp4

**Comment by McPlayHD** [comment]
This has probably been fixed by now or we at least don't get any reports regarding this issue anymore. Either way I'm now closing this issue and if it happens again you can create a new one.
