### ISSUE TITLE
New replays bug

### ISSUE THREAD

**Issue by stupxd** [McPlayHDnet/McPlayHD.net#56]
Today I noticed that my recent replays are bugged - if I go backwards from the end of a replay, half of my bridge disappears. 
I checked old replays and it wasnt happening for them, only for new replays.

https://user-images.githubusercontent.com/83234016/123866330-974f9000-d935-11eb-8e53-c983f85396c2.mp4

https://user-images.githubusercontent.com/83234016/123866340-9880bd00-d935-11eb-824e-46cf6b8d28d6.mp4

**Comment by McPlayHD** [comment]
You probably used some block that disappears after some time. The replays don't respond correctly in that case I'm afraid.

**Comment by stupxd** [comment]
Oh yeah, I just realised that I been using disappearing clay because I can start bridge faster xd Okay then, thanks for explaining.
