### ISSUE TITLE
Bug with reset animations

### ISSUE THREAD

**Issue by ZY-Axis** [McPlayHDnet/McPlayHD.net#59]
The GM1 reset animation can be bugged, and you can have your name show up a ton of times in tab. It also leaves a floating npc. It is caused when gm1 animation is in progress, and you select another animation mid reset. 
![image](https://user-images.githubusercontent.com/87055744/124701490-b1045080-debc-11eb-9c54-c189c6780625.png)

**Comment by McPlayHD** [comment]
Very interesting that no one else found that bug until now xD

**Comment by McPlayHD** [comment]
It should be fixed as soon as the servers restart. After 24 hours all FastBuilder servers should have restarted and the update should be live. If the bug still persists just open this issue again. Thanks for reporting btw @ZY-Axis
