### ISSUE TITLE
Railguns can be used to gain an advantage in the FastBuilder Jump & Run during the dragon spawn event

### ISSUE THREAD

**Issue by MudkiipMC** [McPlayHDnet/McPlayHD.net#61]
Someone in the lobby was telling me and Yellow how they had 8 seconds on the FB JnR, and it turns out they were telling the truth
Apparently, when the Dragon spawn event happens, you can use the railgun boost thing to go faster, and it doesn't cancel the run
I would also like to add that if possible me and Yellow both wouldn't want this person to be banned and just have their pb reset instead, since we talked to them further and it sounds like they were completely unaware that this was not an intentional thing (that the run is not ended) and that they didn't even know it was a bug until we just told them, because they thought it was always possible to do.
![2021-07-20_23 13 23 edit (1)](https://user-images.githubusercontent.com/83512752/126426144-d7105716-54fe-4756-afd7-d6b3c2be1a4a.png)
![2021-07-20_23 14 28 (2)](https://user-images.githubusercontent.com/83512752/126426146-1037c953-98e8-48ff-bfdf-2aa0787b1016.png)
![(3)](https://user-images.githubusercontent.com/83512752/126426158-a9032877-c539-4af3-9366-949738920a53.jpg)

**Comment by MawHealth** [comment]
heres an old clip (1 monthish old, idk if its patched but here)
click youtube video 
https://youtu.be/lzvfiQtn3bw

**Comment by McPlayHD** [comment]
Fixed in the last patch. You will no longer get railguns to kill the dragon.

**Comment by McPlayHD** [comment]
If anyone who used this bug wants their Jump'n'Run stats to be reset please open a support ticket on the discord https://mcplayhd.net/discord and ask a Helper/Mod to tag me.
