### ISSUE TITLE
CakeRush (Infinity) Blocks Bug 

### ISSUE THREAD

**Issue by KnuffigesAppa** [McPlayHDnet/McPlayHD.net#62]
Im folgenden Bug Report geht es um CakeRush.
Es geht darum, dass man sich durch den Bug, der im folgenden näher erläutert wird, so viele Blöcke, wie man möchte erstellen kann. 
Was dazu führt, dass man einen "starken" und unfairen Vorteil gegenüber dem Gegner erlangt.
Erklärung:
Sobald die Runde beginnt ist man in der Lage sein Inventory zu sortieren.
Die "unendlichen" Blöcke erhält man dann dadurch, in dem man den einen Stack Blocks halbiert oder so klein wie möglich macht und in der Leiste zum Beispiel nach Rechts verschiebt. So hat man zum Beispiel 16 Blöcke auf dem ersten Slot ("Main Slot") und auf dem letzten Slot 48 Blöcke. 
Sobald nun einer der Cakes gegessen wird, kriegt man 64 Blöcke zurück und die 48 Blöcke bleiben automatisch auf dem letzten Slot erhalten. Somit kann man diese 48 Blöcke weiter beliebig einsetzten. 
Dazu kann man diesen Bug so oft wiederholen wie man Cakes essen kann.

![2021-07-22_19 57 47](https://user-images.githubusercontent.com/87827851/126692566-5d42edce-cc21-4635-87e0-212ab8e02ac2.png)

**Comment by McPlayHD** [comment]
Fixed with the last patch.
How exactly I changed it will be written in the next changelog.
