### ISSUE TITLE
CR - Elo holograms for invisible players

### ISSUE THREAD

**Issue by stupxd** [McPlayHDnet/McPlayHD.net#65]
If you turn player visibility off, you can still see other players' ELO holograms

![image](https://user-images.githubusercontent.com/83234016/128256950-a8ca0c5b-dea9-473c-9301-2acf9610438b.png)

![image](https://user-images.githubusercontent.com/83234016/128256978-61e0fa6a-8198-4e70-be1a-3097e64e8d34.png)

**Comment by McPlayHD** [comment]
fixed.
