### ISSUE TITLE
Graphical bug with /gift 

### ISSUE THREAD

**Issue by obvTiger** [McPlayHDnet/McPlayHD.net#78]
If you gift someone an amount of emeralds, the receiver of the gift gets in the message in language German 
the message is missing a space between "soeben" and {Amount}
![2021-10-02_09 08 11 (2)](https://user-images.githubusercontent.com/83970850/135724288-a4b5a28c-f2eb-4786-98ec-1b1c54a28639.png)

**Comment by McPlayHD** [comment]
Should be fixed now.
