### ISSUE TITLE
Add some (more) shortcut commands

### ISSUE THREAD

**Issue by TrooperCH** [McPlayHDnet/McPlayHD.net#86]
Person suggested specifically:

- [x] /f -> /friend add
- [x] /fl -> /friend list
- [x] /p -> /party invite
- [x] /p warp -> moves whole party into your lobby
- [x] /qj fb -> joins favourite/random fb lobby for people who already know that they just wanna play fb

Maybe there are more if we think about it

**Comment by McPlayHD** [comment]
Everything has now been implemented from this list.
