### ISSUE TITLE
/afk for vip

### ISSUE THREAD

**Issue by TrooperCH** [McPlayHDnet/McPlayHD.net#88]
Let VIP use /afk to instantly set themselves into afk mode

**Comment by McPlayHD** [comment]
I think we can even let everyone use this command. Players will also be able to set themselves AFK and after one minute they get moved to the limbus. This basically halves the time they still spend in the lobby.

**Comment by McPlayHD** [comment]
This should work as soon as the lobbies are restarted. If not then please reopen this issue.

**Comment by obvTiger** [comment]
Does not work.

**Comment by McPlayHD** [comment]
fixed.
