### ISSUE TITLE
Fix that you can replace grass 

### ISSUE THREAD

**Issue by maksch2** [McPlayHDnet/McPlayHD.net#9]
you can replace the grass (which is on every fb island) with a block. This is unfair, because you can make better tellys with it (says the players)

this: https://i.imgur.com/7QrLOKF.png
to: https://i.imgur.com/nAlNzON.png

**Comment by McPlayHD** [comment]
@IDragonRiderI you handle block places and breaks... Maybe you know why this happens?

**Comment by McPlayHD** [comment]
and @maksch2 is it even a bug or just a clientside thing?

**Comment by maksch2** [comment]
other players cant see the block. Idk. Is that a clientside-thing?

**Comment by maksch2** [comment]
fixed with next fb restarts
