### ISSUE TITLE
/l enhancement

### ISSUE THREAD

**Issue by obvTiger** [McPlayHDnet/McPlayHD.net#96]
if you type in lobby /l the default message You are already connected to this server comes
would be nice if there was a custom message

**Comment by McPlayHD** [comment]
No need. It's kinda obvious that if you are already connected to a server that the server will report that to you. Finding that specific line in the Bungeecord source code and then change it to something else seems a bit unnecessary, doesn't it?

Also you can actually switch lobby's with `/l` if you got connected to lobby02 for some reason but want to be sent to the current active lobby like lobby01.
