### ISSUE TITLE
Stats for infinite

### ISSUE THREAD

**Issue by k-Schnee** [McPlayHDnet/McPlayHD.net#98]
Add stats for infinite mode (max blocks placed / max distance bridged / max average bridging speed)

**Comment by McPlayHD** [comment]
Isn't possible with the stats structure. As stated in https://github.com/McPlayHDnet/McPlayHD.net/issues/80 the system is already complicated like that and specifically spoken: "Every single mode uses the same class as base. If I were to change the Stats table structure I would have to rewrite the whole plugin specifically for this mode"
